### ISSUE TITLE
Calculation folder overwrite

### ISSUE THREAD

**Issue by joaomcteixeira** [Farseer-NMR/FarSeer-NMR#247]
**Current:**
A Run is forbidden when the folders 'spectra' or 'Backbone' or 'Sidechain' exist in the 'Calculation folder', this prevents data overwrite by mistake.

**Problem:**
When the user needs to optimize the calculation parameters he/she needs to run several times the same calculation. It is annoying to have to manually delete the `spectra` and _results_ folders every run.

**Solution:**
A warning message should appears to warn the user that there exists already a calculation stored in the `Calculation folder` - thi is already implemented. A new message should ask the user whether  to overwrite or not.

**Comment by skinnersp** [comment]
That seems simple enough, it would be a flag in the
create_directory_structure routine passed from the warning message.

**Comment by joaomcteixeira** [comment]
Added to project, will be addressed ASAP.
Closing for now
