### ISSUE TITLE
How to organize the transition from standalone to browser based GUI

### ISSUE THREAD

**Issue by joaomcteixeira** [Farseer-NMR/FarSeer-NMR#254]
**Opinion Requiered**

The new GUI should be built and committed to master stepwisely. Durin the building period, the two GUIs should coexist and both could be run independently. When the browser-based gui is ready it should be shifed to main and the other depecrated.

**Comment by skinnersp** [comment]
I agree with this; in fact we might want to leverage a CI/CD pipeline, so we have a dev env and a prod env; things are only pushed to prod after rigorous testing in dev. This would mean two repos and a bit of careful architecting; but that shouldn't be to problematic; baby steps.

**Comment by joaomcteixeira** [comment]
Discussion archived in project. If necessary reopen.
