### ISSUE TITLE
FarsSeer run thumbnails

### ISSUE THREAD

**Issue by miguelarbesu** [Farseer-NMR/FarSeer-NMR#257]
Hi guys,
I am currently working in a paper that requires multiple FarSeer runs to compare a number of peaklists in different manners - for example, different reference peaklists, alternative peaklists for duplicated peaks, etc, and would like to suggest a future improvement.
Such a serial work ends up generating several multiple folders that one often has to revisit several times. It would help saving a small png (as an example, suggestions are welcome) in each results folder showing the FarSeer tree that was used for that particular run. Even in the folder name should reflect this information and it is already stored somewhere in text  format, having a visual guide really helps to rapidly navigate and understand what was done, specially if you already have the FarSeer scheme in mind.
I have not tried to implement this myself since a) I know nothing about GUI coding, and b) I am aware of the future plans for browser-based FarSeer. 
Best regards

**Comment by joaomcteixeira** [comment]
Hi Miguel,
Thanks for your suggestions,
Currently FS tables and pictures have headers to trace their origin, and
folders are organised hierarchically to facilitate guiding. Nonetheless, I
will carefully revisit your suggestions. Surely there are improvements to
be made.

Above all, there will be many improvements that will increase the
modularity of the code to facilitate these implementations.

For the time being, I ask you to please be patient because I am currently
completely away from my computer because I am changing house and city, I
will return fully in August. :-)

All the best,
keep posting
Joao

**Comment by miguelarbesu** [comment]
Hi Joao
Sure, this is only a suggestion for future improvements, not an immediate request!
Rather than help explore a single FarSeer run in detail, this new feature it is intended to quickly inspect "what was I comparing here and how did I organize it". I feel that a view of the tree itself is pretty informative and easy to grasp.
Good luck with your move :)

**Comment by joaomcteixeira** [comment]
I see your point.
Looking forward to implement it,
best and cya :-)
joao

**Comment by skinnersp** [comment]
Hi Miguel/Joao,

Putting a picture of the tree is a feasible and wouldn't take to long to
implement, however, this does open a wider question, namely keeping track
of all calculations in a study, be it NMR or structural biology generally.
This is something that I have been giving a lot of thought to over the past
few months and I am assembling a plan for a software solution that could
tackle this problem.

I will look into getting something drawn to png inside the calculation
folder in the next couple of weeks, once I've got my desk re-assembled etc
- it seems to be a case of getting hold of the boundingRect of the
graphicsView and calling a painter to render it to a pixmap. That being the
case it's no more than 10 lines of code and an hour or so's work to
implement and test.

If I get it done before you find time, Joao, I'll let you know and put it
as a pull request.

Good luck with your move, Joao, and thanks for the suggest Miguel.

Best,
Simon

**Comment by joaomcteixeira** [comment]
Issue tracked in project.
Closing for now, it will be addressed ASAP.
Thank you
