### ISSUE TITLE
Add Kd fitting routines

### ISSUE THREAD

**Issue by skinnersp** [Farseer-NMR/FarSeer-NMR#269]
Include routines for fitting one Kd, two Kd and a general nKd equation. Find published data on BMRB for fitting and create a tutorial which links to this data. If necessary, convert the NMR star into a format that Farseer-NMR supports.

**Comment by joaomcteixeira** [comment]
Tasks registered and catalogued in project, to be addressed as soon as possible.
Reopen if necessary further discussion or and when task becomes under development
Closing for now because it won't be addressed urgently.
