### ISSUE TITLE
Error calculation Routines

### ISSUE THREAD

**Issue by skinnersp** [Farseer-NMR/FarSeer-NMR#270]
There are no error calculation routines for available for our fitting routines, so we should implement a general method for bootstrapping and monte carlo error estimation. This will probably be an extension of the abc for fitting and we'll need to template out a few routines to reduce burden of implementation.

**Comment by joaomcteixeira** [comment]
Tasks registered and catalogued in project, to be addressed as soon as possible.
Reopen if necessary further discussion.
Closing for now because it won't be addressed urgently.
