### ISSUE TITLE
Moving repository to a Farseer-NMR organization dedicated repository.

### ISSUE THREAD

**Issue by joaomcteixeira** [Farseer-NMR/FarSeer-NMR#275]
@JoaoRodrigues suggested the repository should be migrated to a GitHub organization dedicated repository. This will give Farseer-NMR a proper image away from my personal account. This will also facilitate interaction with other developers and organization of our own developing strategies.

With this, I plan to migrate the software during the next weeks.
From this point on we can contribute to the repository by PR from Forks instead of directly cloning the repo.

I have already created the organization account: https://github.com/Farseer-NMR

I need to check how to relink the original link used for the publication to the new Farseer-NMR page.

@skinnersp Do you agree on this?

**Comment by skinnersp** [comment]
I've no objection to this in principal, so long as it facilitates better dev.

**Comment by joaomcteixeira** [comment]
The repository is fully migrated: links are updated in README.md and in Wiki pages.

Thanks to @JoaoRodrigues for all the help!

I am closing this issue - reopen if needed.
